# -*- coding: utf-8 -*-
"""CUSTOMER CHURN RISK ANALYSIS FOR A TELECOM COMPANY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSH1ut16GqRsRjTjqexPsXOIgHIALY1w

## About the Author
**Huzaifa Zia – Data Analyst**  
I enjoy exploring datasets and uncovering insights using Python and Pandas.
Skills: Python, Pandas, NumPy, Matplotlib, Seaborn, Data Visualization, EDA.  
📧 Contact: [Email](553huzaifaziakhan@gmail.com)  

🔗 Social Profiles:  
[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](www.linkedin.com/in/huzaifa-zia-69a869274)  
[![GitHub](https://img.shields.io/badge/GitHub-181717?style=for-the-badge&logo=github&logoColor=white)](https://github.com/HuzaifaZia553)  
[![Kaggle](https://img.shields.io/badge/Kaggle-20BEFF?style=for-the-badge&logo=kaggle&logoColor=white)](https://www.kaggle.com/huzaifaziakhan)

#  LOAD THE DATASET
"""

from google.colab import files
files.upload()

import pandas as pd

"""# Read datset"""

df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

"""# Show all columns"""

pd.set_option('display.max_columns', None)

"""# Display first 5 rows."""

df.head()

df.info()

df.dtypes

df.isnull().sum()

df.duplicated().sum()

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df.describe()

df.columns

"""#  FEATURE CREATION
1. Create Tenure group.
2. Create Monthly charges category.
3. Create Total spending category.
4. Create Contract type category.
"""

bins = [0, 12, 24, 48, 60, 72]
labels = ['0-1 Year', '1-2 Years', '2-4 Years', '4-5 Years', '5-6 Years']

df['Tenure_Group'] = pd.cut(df['tenure'], bins=bins, labels=labels)

bins = [0, 35, 70, 120]
labels = ['Low', 'Medium', 'High']

df['MonthlyCharges_Category'] = pd.cut(df['MonthlyCharges'], bins=bins, labels=labels)

bins = [0, 2000, 5000, 9000]
labels = ['Low Spender', 'Medium Spender', 'High Spender']

df['TotalSpending_Category'] = pd.cut(df['TotalCharges'], bins=bins, labels=labels)

"""# FEATURE SCALING
Apply suitable scaling techniques to Monthly Charges, Total Charges, and Tenure.
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['MonthlyCharges', 'TotalCharges', 'tenure']] = scaler.fit_transform(
    df[['MonthlyCharges', 'TotalCharges', 'tenure']]
)

"""# EXPLORATORY DATA ANALYSIS
1. Identify which contract type has the highest churn.
2. Check whether higher monthly charge increases churn.
3. Check whether longer tenure reduces churn.
4. Identify which payment method has the highest churn rate.
"""

df.groupby('Contract')['Churn'].value_counts(normalize=True).unstack()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Contract', hue='Churn', data=df)
plt.title('Churn by Contract Type')
plt.show()

"""# conclusion
**Month-to-month** → highest churn.
"""

sns.boxplot(x='Churn', y='MonthlyCharges', data=df)
plt.title('Monthly Charges vs Churn')
plt.show()

"""# conclusion
**Customers with higher monthly charges churn more.**
"""

df.groupby('Churn')['MonthlyCharges'].mean()

df.groupby('Churn')['tenure'].mean()

sns.boxplot(x='Churn', y='tenure', data=df)
plt.title('Tenure vs Churn')
plt.show()

""" # conclusion
 **Customers with short tenure churn more**
"""

df.groupby('PaymentMethod')['Churn'].value_counts(normalize=True).unstack()

sns.countplot(x='PaymentMethod', hue='Churn', data=df)
plt.xticks(rotation=45)
plt.title('Churn by Payment Method')
plt.show()

"""# Conclusion
**Electronic check has the highest churn.**
"""

sns.barplot(x='Contract', y='MonthlyCharges', data=df)
plt.title('Average Monthly Charges by Contract')
plt.show()

plt.hist(df['tenure'], bins=30)
plt.title('Distribution of Tenure')
plt.xlabel('Tenure')
plt.ylabel('Frequency')
plt.show()

sns.scatterplot(x='tenure', y='MonthlyCharges', data=df)
plt.title('Tenure vs Monthly Charges')
plt.show()

df['Churn'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title('Churn Distribution')
plt.ylabel('')
plt.show()

sns.regplot(x='tenure', y='TotalCharges', data=df)
plt.title('Tenure vs Total Charges')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Select numeric columns only
numeric_cols = ['tenure','MonthlyCharges','TotalCharges']

# Correlation matrix
corr_matrix = df[numeric_cols].corr()
print(corr_matrix)

# Heatmap visualization
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""# Shorter tenure → more churn

**Higher monthly charges → more churn**
**Lower total spending → more churn (new customers)**
"""

df.groupby('Churn')[numeric_cols].mean()

churn_rate = df.groupby('Contract')['Churn'].value_counts(normalize=True).unstack()
churn_rate

high_risk = df[
    (df['Contract'] == 'Month-to-month') &
    (df['MonthlyCharges'] > df['MonthlyCharges'].median()) &
    (df['tenure'] < 12)
]
high_risk[['customerID','tenure','MonthlyCharges','Contract','PaymentMethod','Churn']]

churn_rate = df.groupby('Contract')['Churn'].value_counts(normalize=True).unstack()
churn_rate

"""# Conclusion
**Long-term contracts = safest for the company**.

##  Retention Strategies

Based on the EDA, the following strategies can help reduce customer churn:

### 1. Target High-Risk Customers
- Focus on customers with **month-to-month contracts**, **high monthly charges**, and **low tenure**.
- Identify these customers for personalized retention campaigns.

### 2. Offer Incentives to Switch to Long-Term Contracts
- Provide **discounted yearly plans**.
- Implement **loyalty programs** to encourage longer commitments.

### 3. Promote Add-On Services
- Encourage adoption of **TechSupport, DeviceProtection, OnlineSecurity**, etc.
- Customers with **more services** are less likely to churn.

### 4. Payment Method Adjustments
- Encourage **automatic payments** instead of **electronic check**.
- Reduce failed payments and payment-related issues.

### 5. Customer Engagement
- Send **proactive emails** for engagement and updates.
- Provide **rewards for tenure** or consistent usage.
- Offer **early support for complaints** to improve customer satisfaction.
"""